bpkg:
  - package: rafaelcalleja/assert.sh:v1.1
    installPath: ./deps
  - package: Dokify/repository-templates:0.0.76
    installPath: deps/
    token: "${GH_TOKEN}"
    package_json: |
      {
        "name": "repository-templates",
        "version": "0.0.76",
        "files": [ "src/pre-commit/.pre-commit-config.yaml" ] 
      }
