name: bpkg repository

on:
  push:
    paths:
      - '.bpkg.yml'
      - 'deps/**'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: BPKG Repository
        uses: rafaelcalleja/bpkg-action@0.0.1
      - name: Bump Deps
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add -f deps
          (git commit -m "bump deps" && git push) || true
